# =============================================================================
# PPI - aCSM Split
# =============================================================================
# Usage: python scripts/train_ppi.py --config configs/ppi_acsm.yaml

data:
  split_name: acsm
  train_file: ./data/downstream/propedia_ppi_acsm_train.csv
  test_file: ./data/downstream/propedia_ppi_acsm_test.csv
